const MoviesActionTypes = {
    FETCH_MOVIES_START: 'FETCH_MOVIES_START',
    FETCH_MOVIES_SUCCESS: 'FETCH_MOVIES_SUCCESS',
    FETCH_MOVIES_FAILURE: 'FETCH_MOVIES_FAILURE',
    ADD_QUERY_RESULTS: 'ADD_QUERY_RESULTS',
    ADD_QUERY_INFO: 'ADD_QUERY_INFO',
    ADD_WATCHED: 'ADD_WATCHED',
    ADD_FAVORITES: 'ADD_FAVORITES',
    CLEAR_FROM_FAVORITES: 'CLEAR_FROM_FAVORITES',
    CLEAR_FROM_WATCHED: 'CLEAR_FROM_WATCHED',
    SORT_TITLE: 'SORT_TITLE',
    SORT_POPULAR: 'SORT_POPULAR',
  };
  
  export default MoviesActionTypes;